-- 项目配置 (xiàngmù pèizhì — project configuration)
set_xmakever("3.0.0")
set_project("speedmath")
set_version("1.0.0")
set_languages("c++20")

-- 静态库 (jìngtài kù — static library): 核心游戏逻辑 (héxīn yóuxì luóji — core game logic)
target("libspeedmath")
    set_kind("static")
    add_files("libspeedmath/*.cpp")
    add_includedirs(".")

-- 后端服务器 (hòuduān fúwùqì — backend server)
target("backend")
    set_kind("binary")
    add_files("backend/main.cpp")
    add_deps("libspeedmath")
    add_includedirs("backend")
    add_syslinks("sqlite3")

-- 可执行文件 (kě zhíxíng wénjiàn — executable binary): 控制台入口 (kòngzhìtái rùkǒu — console entry point)
target("speedmath")
    set_kind("binary")
    add_files("main.cpp")
    add_deps("libspeedmath")

-- 测试 (cèshì — tests): runs all unit tests
target("tests")
    set_kind("binary")
    add_files("tests/test_*.cpp")
    add_deps("libspeedmath")
    add_includedirs("tests")

-- 数据库测试 (shùjùkù cèshì — database test)
target("test_db")
    set_kind("binary")
    add_files("tests/test_db.cpp")
    add_includedirs("backend")
    add_syslinks("sqlite3")
